//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entities.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a aeronave..
        /// </summary>
        public static string aeronaveVazio {
            get {
                return ResourceManager.GetString("aeronaveVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano inválido (1900 a 2200)..
        /// </summary>
        public static string anoInvalido {
            get {
                return ResourceManager.GetString("anoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Ano&apos;..
        /// </summary>
        public static string anoVazio {
            get {
                return ResourceManager.GetString("anoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a área..
        /// </summary>
        public static string areaVazio {
            get {
                return ResourceManager.GetString("areaVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Atendimento&apos;..
        /// </summary>
        public static string atendimentoVazio {
            get {
                return ResourceManager.GetString("atendimentoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o canal..
        /// </summary>
        public static string canalVazio {
            get {
                return ResourceManager.GetString("canalVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Cep&apos; inválido (00000000)..
        /// </summary>
        public static string cepInvalido {
            get {
                return ResourceManager.GetString("cepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o estado/cidade..
        /// </summary>
        public static string cidadeVazio {
            get {
                return ResourceManager.GetString("cidadeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a classificação..
        /// </summary>
        public static string classificacaoVazio {
            get {
                return ResourceManager.GetString("classificacaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a conversão..
        /// </summary>
        public static string conversaoVazio {
            get {
                return ResourceManager.GetString("conversaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Cor&apos; deve conter 6 letras (A-F)..
        /// </summary>
        public static string cor6 {
            get {
                return ResourceManager.GetString("cor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;CPF/CNPJ&apos; excedido (14)..
        /// </summary>
        public static string cpfCnpjInvalido {
            get {
                return ResourceManager.GetString("cpfCnpjInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Data início&apos;..
        /// </summary>
        public static string dataInicioVazio {
            get {
                return ResourceManager.GetString("dataInicioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Data término&apos;..
        /// </summary>
        public static string dataTerminoVazio {
            get {
                return ResourceManager.GetString("dataTerminoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Data&apos;..
        /// </summary>
        public static string dataVazio {
            get {
                return ResourceManager.GetString("dataVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;DDD&apos; excedido (2)..
        /// </summary>
        public static string dddInvalido {
            get {
                return ResourceManager.GetString("dddInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;DDD&apos;..
        /// </summary>
        public static string dddVazio {
            get {
                return ResourceManager.GetString("dddVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;DDI&apos; excedido (2)..
        /// </summary>
        public static string ddiInvalido {
            get {
                return ResourceManager.GetString("ddiInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Descrição&apos;..
        /// </summary>
        public static string descricaoVazio {
            get {
                return ResourceManager.GetString("descricaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Dia início&apos;..
        /// </summary>
        public static string diaInicioVazio {
            get {
                return ResourceManager.GetString("diaInicioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Dia término&apos;..
        /// </summary>
        public static string diaTerminoVazio {
            get {
                return ResourceManager.GetString("diaTerminoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;E-mail&apos; excedido (100)..
        /// </summary>
        public static string email100 {
            get {
                return ResourceManager.GetString("email100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;E-mail&apos;..
        /// </summary>
        public static string emailVazio {
            get {
                return ResourceManager.GetString("emailVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a empresa..
        /// </summary>
        public static string entidadeVazio {
            get {
                return ResourceManager.GetString("entidadeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o fabricante..
        /// </summary>
        public static string fabricanteVazio {
            get {
                return ResourceManager.GetString("fabricanteVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Login&apos; excedido (50)..
        /// </summary>
        public static string login50 {
            get {
                return ResourceManager.GetString("login50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Login&apos;..
        /// </summary>
        public static string loginVazio {
            get {
                return ResourceManager.GetString("loginVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Logradouro&apos; excedido (200)..
        /// </summary>
        public static string logradouroInvalido {
            get {
                return ResourceManager.GetString("logradouroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Meta&apos;..
        /// </summary>
        public static string metaVazio {
            get {
                return ResourceManager.GetString("metaVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Modelo&apos; excedido (100)..
        /// </summary>
        public static string modelo100 {
            get {
                return ResourceManager.GetString("modelo100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Modelo&apos;..
        /// </summary>
        public static string modeloVazio {
            get {
                return ResourceManager.GetString("modeloVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a motorização..
        /// </summary>
        public static string motorizacaoVazio {
            get {
                return ResourceManager.GetString("motorizacaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Nome&apos; excedido (100)..
        /// </summary>
        public static string nome100 {
            get {
                return ResourceManager.GetString("nome100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Nome&apos; excedido (150)..
        /// </summary>
        public static string nome150 {
            get {
                return ResourceManager.GetString("nome150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Nome&apos; excedido (50)..
        /// </summary>
        public static string nome50 {
            get {
                return ResourceManager.GetString("nome50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Nome&apos;..
        /// </summary>
        public static string nomeVazio {
            get {
                return ResourceManager.GetString("nomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Número&apos; excedido (6)..
        /// </summary>
        public static string numeroInvalido {
            get {
                return ResourceManager.GetString("numeroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Número&apos;..
        /// </summary>
        public static string numeroVazio {
            get {
                return ResourceManager.GetString("numeroVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de ordem inválida (1 a 99)..
        /// </summary>
        public static string ordemInvalida {
            get {
                return ResourceManager.GetString("ordemInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Ordem&apos;..
        /// </summary>
        public static string ordemVazia {
            get {
                return ResourceManager.GetString("ordemVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o perfil..
        /// </summary>
        public static string perfilVazio {
            get {
                return ResourceManager.GetString("perfilVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a &apos;Pessoa&apos;..
        /// </summary>
        public static string pessoaVazio {
            get {
                return ResourceManager.GetString("pessoaVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Porcentagem final&apos;..
        /// </summary>
        public static string porcentagemFinalVazio {
            get {
                return ResourceManager.GetString("porcentagemFinalVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Porcentagem inicial&apos;..
        /// </summary>
        public static string porcentagemInicialVazio {
            get {
                return ResourceManager.GetString("porcentagemInicialVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentagem inválida..
        /// </summary>
        public static string porcentagemInvalida {
            get {
                return ResourceManager.GetString("porcentagemInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;Prefixo&apos; deve ter 5 letras..
        /// </summary>
        public static string prefixoInvalido {
            get {
                return ResourceManager.GetString("prefixoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Prefixo&apos;..
        /// </summary>
        public static string prefixoVazio {
            get {
                return ResourceManager.GetString("prefixoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o setor..
        /// </summary>
        public static string setorVazio {
            get {
                return ResourceManager.GetString("setorVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a situação..
        /// </summary>
        public static string situacaoVazio {
            get {
                return ResourceManager.GetString("situacaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Sobrenome&apos; excedido (50)..
        /// </summary>
        public static string sobrenome50 {
            get {
                return ResourceManager.GetString("sobrenome50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o campo &apos;Sobrenome&apos;..
        /// </summary>
        public static string sobrenomeVazio {
            get {
                return ResourceManager.GetString("sobrenomeVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o &apos;Status&apos;..
        /// </summary>
        public static string statusVazio {
            get {
                return ResourceManager.GetString("statusVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o tipo de meta..
        /// </summary>
        public static string tipoMetaVazio {
            get {
                return ResourceManager.GetString("tipoMetaVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o tipo..
        /// </summary>
        public static string tipoVazio {
            get {
                return ResourceManager.GetString("tipoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o usuário..
        /// </summary>
        public static string usuarioVazio {
            get {
                return ResourceManager.GetString("usuarioVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho do campo &apos;Website&apos; excedido (100)..
        /// </summary>
        public static string websiteInvalido {
            get {
                return ResourceManager.GetString("websiteInvalido", resourceCulture);
            }
        }
    }
}
