//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAMINTEGRA.WS_Avalara_Connect {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoReqDto", Namespace="http://schemas.datacontract.org/2004/07/Efisc.MonitorNFe.ConsumoWS.Dto")]
    [System.SerializableAttribute()]
    public partial class EventoReqDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveNFeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveNFe {
            get {
                return this.ChaveNFeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveNFeField, value) != true)) {
                    this.ChaveNFeField = value;
                    this.RaisePropertyChanged("ChaveNFe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEvento {
            get {
                return this.TipoEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEventoField, value) != true)) {
                    this.TipoEventoField = value;
                    this.RaisePropertyChanged("TipoEvento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoRespDto", Namespace="http://schemas.datacontract.org/2004/07/Efisc.MonitorNFe.ConsumoWS.Dto")]
    [System.SerializableAttribute()]
    public partial class EventoRespDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveNFeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SucessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveNFe {
            get {
                return this.ChaveNFeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveNFeField, value) != true)) {
                    this.ChaveNFeField = value;
                    this.RaisePropertyChanged("ChaveNFe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sucesso {
            get {
                return this.SucessoField;
            }
            set {
                if ((this.SucessoField.Equals(value) != true)) {
                    this.SucessoField = value;
                    this.RaisePropertyChanged("Sucesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoCTeReqDto", Namespace="http://schemas.datacontract.org/2004/07/Efisc.MonitorNFe.ConsumoWS.Dto")]
    [System.SerializableAttribute()]
    public partial class EventoCTeReqDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveCTeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveCTe {
            get {
                return this.ChaveCTeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveCTeField, value) != true)) {
                    this.ChaveCTeField = value;
                    this.RaisePropertyChanged("ChaveCTe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Motivo {
            get {
                return this.MotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoField, value) != true)) {
                    this.MotivoField = value;
                    this.RaisePropertyChanged("Motivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEvento {
            get {
                return this.TipoEventoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEventoField, value) != true)) {
                    this.TipoEventoField = value;
                    this.RaisePropertyChanged("TipoEvento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoCTeRespDto", Namespace="http://schemas.datacontract.org/2004/07/Efisc.MonitorNFe.ConsumoWS.Dto")]
    [System.SerializableAttribute()]
    public partial class EventoCTeRespDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveCTeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SucessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveCTe {
            get {
                return this.ChaveCTeField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveCTeField, value) != true)) {
                    this.ChaveCTeField = value;
                    this.RaisePropertyChanged("ChaveCTe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sucesso {
            get {
                return this.SucessoField;
            }
            set {
                if ((this.SucessoField.Equals(value) != true)) {
                    this.SucessoField = value;
                    this.RaisePropertyChanged("Sucesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Avalara_Connect.IConsumoWS")]
    public interface IConsumoWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/ConectividadeWS", ReplyAction="http://tempuri.org/IConsumoWS/ConectividadeWSResponse")]
        string ConectividadeWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/ConectividadeWS", ReplyAction="http://tempuri.org/IConsumoWS/ConectividadeWSResponse")]
        System.Threading.Tasks.Task<string> ConectividadeWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadNFe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadNFeResponse")]
        string DownloadNFe(string usuario, string senha, string chaveNfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadNFe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadNFeResponse")]
        System.Threading.Tasks.Task<string> DownloadNFeAsync(string usuario, string senha, string chaveNfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/Login", ReplyAction="http://tempuri.org/IConsumoWS/LoginResponse")]
        System.Nullable<int> Login(string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/Login", ReplyAction="http://tempuri.org/IConsumoWS/LoginResponse")]
        System.Threading.Tasks.Task<System.Nullable<int>> LoginAsync(string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFe", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFeResponse")]
        string RetornaChavesNFe(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFe", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFeResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesNFeAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaResumosNFes", ReplyAction="http://tempuri.org/IConsumoWS/RetornaResumosNFesResponse")]
        string RetornaResumosNFes(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaResumosNFes", ReplyAction="http://tempuri.org/IConsumoWS/RetornaResumosNFesResponse")]
        System.Threading.Tasks.Task<string> RetornaResumosNFesAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, int pagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaClassificacoesProdutos", ReplyAction="http://tempuri.org/IConsumoWS/RetornaClassificacoesProdutosResponse")]
        string RetornaClassificacoesProdutos(string usuario, string senha, string chaveeletronica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaClassificacoesProdutos", ReplyAction="http://tempuri.org/IConsumoWS/RetornaClassificacoesProdutosResponse")]
        System.Threading.Tasks.Task<string> RetornaClassificacoesProdutosAsync(string usuario, string senha, string chaveeletronica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesCTePorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesCTePorTipoResponse")]
        string RetornaChavesCTePorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesCTePorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesCTePorTipoResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesCTePorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFes", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesResponse")]
        string RetornaXMLNFes(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFes", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLNFesAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEntradaPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEntradaPorTipoResponse")]
        string RetornaXMLNFesPelaEntradaPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEntradaPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEntradaPorTipoResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLNFesPelaEntradaPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaEmissaoResponse")]
        string RetornaChavesNFePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesNFePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissaoResponse")]
        string RetornaXMLNFesPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLNFesPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissaoPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissaoPorTipoResponse")]
        string RetornaXMLNFesPelaEmissaoPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissaoPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFesPelaEmissaoPorTipoResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLNFesPelaEmissaoPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadCTe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadCTeResponse")]
        string DownloadCTe(string usuario, string senha, string chaveCTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadCTe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadCTeResponse")]
        System.Threading.Tasks.Task<string> DownloadCTeAsync(string usuario, string senha, string chaveCTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissaoResponse")]
        string RetornaXMLCTesPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntradaResponse")]
        string RetornaXMLCTesPelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntradaResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissaoPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissaoPorTipoResponse")]
        string RetornaXMLCTesPelaEmissaoPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissaoPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEmissaoPorTipoResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEmissaoPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntradaPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntradaPorTipoResponse")]
        string RetornaXMLCTesPelaEntradaPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntradaPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLCTesPelaEntradaPorTipoResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEntradaPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadNfse", ReplyAction="http://tempuri.org/IConsumoWS/DownloadNfseResponse")]
        string DownloadNfse(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadNfse", ReplyAction="http://tempuri.org/IConsumoWS/DownloadNfseResponse")]
        System.Threading.Tasks.Task<string> DownloadNfseAsync(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEmissaoResponse")]
        string RetornaXMLNFSePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLNFSePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEmissaoResponse")]
        string RetornaChavesNFSePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesNFSePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEntradaResponse")]
        string RetornaChavesNFSeAprovadasPelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEntradaResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesNFSeAprovadasPelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEmissaoResponse")]
        string RetornaChavesNFSeAprovadasPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSeAprovadasPelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesNFSeAprovadasPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEntradaResponse")]
        string RetornaXMLNFSePelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaXMLNFSePelaEntradaResponse")]
        System.Threading.Tasks.Task<string> RetornaXMLNFSePelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEntradaResponse")]
        string RetornaChavesNFSePelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFSePelaEntradaResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesNFSePelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RealizarManifestoNFe", ReplyAction="http://tempuri.org/IConsumoWS/RealizarManifestoNFeResponse")]
        TAMINTEGRA.WS_Avalara_Connect.EventoRespDto RealizarManifestoNFe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RealizarManifestoNFe", ReplyAction="http://tempuri.org/IConsumoWS/RealizarManifestoNFeResponse")]
        System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoRespDto> RealizarManifestoNFeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RealizarLoteManifestoNFe", ReplyAction="http://tempuri.org/IConsumoWS/RealizarLoteManifestoNFeResponse")]
        TAMINTEGRA.WS_Avalara_Connect.EventoRespDto[] RealizarLoteManifestoNFe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto[] eventos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RealizarLoteManifestoNFe", ReplyAction="http://tempuri.org/IConsumoWS/RealizarLoteManifestoNFeResponse")]
        System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoRespDto[]> RealizarLoteManifestoNFeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto[] eventos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornarChavesIntegracao", ReplyAction="http://tempuri.org/IConsumoWS/RetornarChavesIntegracaoResponse")]
        string RetornarChavesIntegracao(string usuario, string senha, int companhia, int estabelecimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornarChavesIntegracao", ReplyAction="http://tempuri.org/IConsumoWS/RetornarChavesIntegracaoResponse")]
        System.Threading.Tasks.Task<string> RetornarChavesIntegracaoAsync(string usuario, string senha, int companhia, int estabelecimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornarChavesCTeIntegracao", ReplyAction="http://tempuri.org/IConsumoWS/RetornarChavesCTeIntegracaoResponse")]
        string RetornarChavesCTeIntegracao(string usuario, string senha, int companhia, int estabelecimento, int tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornarChavesCTeIntegracao", ReplyAction="http://tempuri.org/IConsumoWS/RetornarChavesCTeIntegracaoResponse")]
        System.Threading.Tasks.Task<string> RetornarChavesCTeIntegracaoAsync(string usuario, string senha, int companhia, int estabelecimento, int tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/PesquisarStatusEventoNFe", ReplyAction="http://tempuri.org/IConsumoWS/PesquisarStatusEventoNFeResponse")]
        TAMINTEGRA.WS_Avalara_Connect.EventoRespDto PesquisarStatusEventoNFe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/PesquisarStatusEventoNFe", ReplyAction="http://tempuri.org/IConsumoWS/PesquisarStatusEventoNFeResponse")]
        System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoRespDto> PesquisarStatusEventoNFeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaNovaUrlSaS", ReplyAction="http://tempuri.org/IConsumoWS/RetornaNovaUrlSaSResponse")]
        string RetornaNovaUrlSaS(string oldUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaNovaUrlSaS", ReplyAction="http://tempuri.org/IConsumoWS/RetornaNovaUrlSaSResponse")]
        System.Threading.Tasks.Task<string> RetornaNovaUrlSaSAsync(string oldUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadPdfNfe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadPdfNfeResponse")]
        string DownloadPdfNfe(string usuario, string senha, string chaveNfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadPdfNfe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadPdfNfeResponse")]
        System.Threading.Tasks.Task<string> DownloadPdfNfeAsync(string usuario, string senha, string chaveNfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaCapas", ReplyAction="http://tempuri.org/IConsumoWS/RetornaCapasResponse")]
        string RetornaCapas(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo, string capa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaCapas", ReplyAction="http://tempuri.org/IConsumoWS/RetornaCapasResponse")]
        System.Threading.Tasks.Task<string> RetornaCapasAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo, string capa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaDataEntradaXml", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaDataEntradaXmlResponse")]
        string RetornaChavesNFePelaDataEntradaXml(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaDataEntradaXml", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesNFePelaDataEntradaXmlResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesNFePelaDataEntradaXmlAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/IntegracaoFisicaFiscal", ReplyAction="http://tempuri.org/IConsumoWS/IntegracaoFisicaFiscalResponse")]
        string IntegracaoFisicaFiscal(string usuario, string senha, string sFileName, byte[] fileContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/IntegracaoFisicaFiscal", ReplyAction="http://tempuri.org/IConsumoWS/IntegracaoFisicaFiscalResponse")]
        System.Threading.Tasks.Task<string> IntegracaoFisicaFiscalAsync(string usuario, string senha, string sFileName, byte[] fileContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/PesquisarStatusSefazNFe", ReplyAction="http://tempuri.org/IConsumoWS/PesquisarStatusSefazNFeResponse")]
        string PesquisarStatusSefazNFe(string usuario, string senha, string chaveNFe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/PesquisarStatusSefazNFe", ReplyAction="http://tempuri.org/IConsumoWS/PesquisarStatusSefazNFeResponse")]
        System.Threading.Tasks.Task<string> PesquisarStatusSefazNFeAsync(string usuario, string senha, string chaveNFe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadPdfCTe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadPdfCTeResponse")]
        string DownloadPdfCTe(string usuario, string senha, string chaveCTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadPdfCTe", ReplyAction="http://tempuri.org/IConsumoWS/DownloadPdfCTeResponse")]
        System.Threading.Tasks.Task<string> DownloadPdfCTeAsync(string usuario, string senha, string chaveCTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEmissaoResponse")]
        string RetornaPdfCTesPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaPdfCTesPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEntradaResponse")]
        string RetornaPdfCTesPelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfCTesPelaEntradaResponse")]
        System.Threading.Tasks.Task<string> RetornaPdfCTesPelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadPdfNfse", ReplyAction="http://tempuri.org/IConsumoWS/DownloadPdfNfseResponse")]
        string DownloadPdfNfse(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/DownloadPdfNfse", ReplyAction="http://tempuri.org/IConsumoWS/DownloadPdfNfseResponse")]
        System.Threading.Tasks.Task<string> DownloadPdfNfseAsync(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEmissaoResponse")]
        string RetornaPdfNFSePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEmissao", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEmissaoResponse")]
        System.Threading.Tasks.Task<string> RetornaPdfNFSePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEntradaResponse")]
        string RetornaPdfNFSePelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEntrada", ReplyAction="http://tempuri.org/IConsumoWS/RetornaPdfNFSePelaEntradaResponse")]
        System.Threading.Tasks.Task<string> RetornaPdfNFSePelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesCTePelaEntradaPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesCTePelaEntradaPorTipoResponse")]
        string RetornaChavesCTePelaEntradaPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RetornaChavesCTePelaEntradaPorTipo", ReplyAction="http://tempuri.org/IConsumoWS/RetornaChavesCTePelaEntradaPorTipoResponse")]
        System.Threading.Tasks.Task<string> RetornaChavesCTePelaEntradaPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RealizarManifestoCTe", ReplyAction="http://tempuri.org/IConsumoWS/RealizarManifestoCTeResponse")]
        TAMINTEGRA.WS_Avalara_Connect.EventoCTeRespDto RealizarManifestoCTe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoCTeReqDto evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConsumoWS/RealizarManifestoCTe", ReplyAction="http://tempuri.org/IConsumoWS/RealizarManifestoCTeResponse")]
        System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoCTeRespDto> RealizarManifestoCTeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoCTeReqDto evento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsumoWSChannel : TAMINTEGRA.WS_Avalara_Connect.IConsumoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsumoWSClient : System.ServiceModel.ClientBase<TAMINTEGRA.WS_Avalara_Connect.IConsumoWS>, TAMINTEGRA.WS_Avalara_Connect.IConsumoWS {
        
        public ConsumoWSClient() {
        }
        
        public ConsumoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsumoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConectividadeWS() {
            return base.Channel.ConectividadeWS();
        }
        
        public System.Threading.Tasks.Task<string> ConectividadeWSAsync() {
            return base.Channel.ConectividadeWSAsync();
        }
        
        public string DownloadNFe(string usuario, string senha, string chaveNfe) {
            return base.Channel.DownloadNFe(usuario, senha, chaveNfe);
        }
        
        public System.Threading.Tasks.Task<string> DownloadNFeAsync(string usuario, string senha, string chaveNfe) {
            return base.Channel.DownloadNFeAsync(usuario, senha, chaveNfe);
        }
        
        public System.Nullable<int> Login(string usuario, string senha) {
            return base.Channel.Login(usuario, senha);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<int>> LoginAsync(string usuario, string senha) {
            return base.Channel.LoginAsync(usuario, senha);
        }
        
        public string RetornaChavesNFe(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaChavesNFe(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesNFeAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaChavesNFeAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaResumosNFes(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, int pagina) {
            return base.Channel.RetornaResumosNFes(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, pagina);
        }
        
        public System.Threading.Tasks.Task<string> RetornaResumosNFesAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, int pagina) {
            return base.Channel.RetornaResumosNFesAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, pagina);
        }
        
        public string RetornaClassificacoesProdutos(string usuario, string senha, string chaveeletronica) {
            return base.Channel.RetornaClassificacoesProdutos(usuario, senha, chaveeletronica);
        }
        
        public System.Threading.Tasks.Task<string> RetornaClassificacoesProdutosAsync(string usuario, string senha, string chaveeletronica) {
            return base.Channel.RetornaClassificacoesProdutosAsync(usuario, senha, chaveeletronica);
        }
        
        public string RetornaChavesCTePorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesCTePorTipo(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesCTePorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesCTePorTipoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string RetornaXMLNFes(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFes(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLNFesAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFesAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaXMLNFesPelaEntradaPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLNFesPelaEntradaPorTipo(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLNFesPelaEntradaPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLNFesPelaEntradaPorTipoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string RetornaChavesNFePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaChavesNFePelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesNFePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaChavesNFePelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaXMLNFesPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFesPelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLNFesPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFesPelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaXMLNFesPelaEmissaoPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLNFesPelaEmissaoPorTipo(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLNFesPelaEmissaoPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLNFesPelaEmissaoPorTipoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string DownloadCTe(string usuario, string senha, string chaveCTe) {
            return base.Channel.DownloadCTe(usuario, senha, chaveCTe);
        }
        
        public System.Threading.Tasks.Task<string> DownloadCTeAsync(string usuario, string senha, string chaveCTe) {
            return base.Channel.DownloadCTeAsync(usuario, senha, chaveCTe);
        }
        
        public string RetornaXMLCTesPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLCTesPelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLCTesPelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaXMLCTesPelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLCTesPelaEntrada(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLCTesPelaEntradaAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaXMLCTesPelaEmissaoPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLCTesPelaEmissaoPorTipo(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEmissaoPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLCTesPelaEmissaoPorTipoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string RetornaXMLCTesPelaEntradaPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLCTesPelaEntradaPorTipo(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLCTesPelaEntradaPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaXMLCTesPelaEntradaPorTipoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string DownloadNfse(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento) {
            return base.Channel.DownloadNfse(usuario, senha, NumeroDocumento, DataEmissaoDocumento, CNPJEmissorDocumento);
        }
        
        public System.Threading.Tasks.Task<string> DownloadNfseAsync(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento) {
            return base.Channel.DownloadNfseAsync(usuario, senha, NumeroDocumento, DataEmissaoDocumento, CNPJEmissorDocumento);
        }
        
        public string RetornaXMLNFSePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFSePelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLNFSePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFSePelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaChavesNFSePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSePelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesNFSePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSePelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string RetornaChavesNFSeAprovadasPelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSeAprovadasPelaEntrada(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesNFSeAprovadasPelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSeAprovadasPelaEntradaAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string RetornaChavesNFSeAprovadasPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSeAprovadasPelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesNFSeAprovadasPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSeAprovadasPelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public string RetornaXMLNFSePelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFSePelaEntrada(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaXMLNFSePelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaXMLNFSePelaEntradaAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaChavesNFSePelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSePelaEntrada(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesNFSePelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesNFSePelaEntradaAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public TAMINTEGRA.WS_Avalara_Connect.EventoRespDto RealizarManifestoNFe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento) {
            return base.Channel.RealizarManifestoNFe(usuario, senha, evento);
        }
        
        public System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoRespDto> RealizarManifestoNFeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento) {
            return base.Channel.RealizarManifestoNFeAsync(usuario, senha, evento);
        }
        
        public TAMINTEGRA.WS_Avalara_Connect.EventoRespDto[] RealizarLoteManifestoNFe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto[] eventos) {
            return base.Channel.RealizarLoteManifestoNFe(usuario, senha, eventos);
        }
        
        public System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoRespDto[]> RealizarLoteManifestoNFeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto[] eventos) {
            return base.Channel.RealizarLoteManifestoNFeAsync(usuario, senha, eventos);
        }
        
        public string RetornarChavesIntegracao(string usuario, string senha, int companhia, int estabelecimento) {
            return base.Channel.RetornarChavesIntegracao(usuario, senha, companhia, estabelecimento);
        }
        
        public System.Threading.Tasks.Task<string> RetornarChavesIntegracaoAsync(string usuario, string senha, int companhia, int estabelecimento) {
            return base.Channel.RetornarChavesIntegracaoAsync(usuario, senha, companhia, estabelecimento);
        }
        
        public string RetornarChavesCTeIntegracao(string usuario, string senha, int companhia, int estabelecimento, int tipo) {
            return base.Channel.RetornarChavesCTeIntegracao(usuario, senha, companhia, estabelecimento, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornarChavesCTeIntegracaoAsync(string usuario, string senha, int companhia, int estabelecimento, int tipo) {
            return base.Channel.RetornarChavesCTeIntegracaoAsync(usuario, senha, companhia, estabelecimento, tipo);
        }
        
        public TAMINTEGRA.WS_Avalara_Connect.EventoRespDto PesquisarStatusEventoNFe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento) {
            return base.Channel.PesquisarStatusEventoNFe(usuario, senha, evento);
        }
        
        public System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoRespDto> PesquisarStatusEventoNFeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoReqDto evento) {
            return base.Channel.PesquisarStatusEventoNFeAsync(usuario, senha, evento);
        }
        
        public string RetornaNovaUrlSaS(string oldUrl) {
            return base.Channel.RetornaNovaUrlSaS(oldUrl);
        }
        
        public System.Threading.Tasks.Task<string> RetornaNovaUrlSaSAsync(string oldUrl) {
            return base.Channel.RetornaNovaUrlSaSAsync(oldUrl);
        }
        
        public string DownloadPdfNfe(string usuario, string senha, string chaveNfe) {
            return base.Channel.DownloadPdfNfe(usuario, senha, chaveNfe);
        }
        
        public System.Threading.Tasks.Task<string> DownloadPdfNfeAsync(string usuario, string senha, string chaveNfe) {
            return base.Channel.DownloadPdfNfeAsync(usuario, senha, chaveNfe);
        }
        
        public string RetornaCapas(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo, string capa) {
            return base.Channel.RetornaCapas(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo, capa);
        }
        
        public System.Threading.Tasks.Task<string> RetornaCapasAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo, string capa) {
            return base.Channel.RetornaCapasAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo, capa);
        }
        
        public string RetornaChavesNFePelaDataEntradaXml(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaChavesNFePelaDataEntradaXml(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesNFePelaDataEntradaXmlAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaChavesNFePelaDataEntradaXmlAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string IntegracaoFisicaFiscal(string usuario, string senha, string sFileName, byte[] fileContent) {
            return base.Channel.IntegracaoFisicaFiscal(usuario, senha, sFileName, fileContent);
        }
        
        public System.Threading.Tasks.Task<string> IntegracaoFisicaFiscalAsync(string usuario, string senha, string sFileName, byte[] fileContent) {
            return base.Channel.IntegracaoFisicaFiscalAsync(usuario, senha, sFileName, fileContent);
        }
        
        public string PesquisarStatusSefazNFe(string usuario, string senha, string chaveNFe) {
            return base.Channel.PesquisarStatusSefazNFe(usuario, senha, chaveNFe);
        }
        
        public System.Threading.Tasks.Task<string> PesquisarStatusSefazNFeAsync(string usuario, string senha, string chaveNFe) {
            return base.Channel.PesquisarStatusSefazNFeAsync(usuario, senha, chaveNFe);
        }
        
        public string DownloadPdfCTe(string usuario, string senha, string chaveCTe) {
            return base.Channel.DownloadPdfCTe(usuario, senha, chaveCTe);
        }
        
        public System.Threading.Tasks.Task<string> DownloadPdfCTeAsync(string usuario, string senha, string chaveCTe) {
            return base.Channel.DownloadPdfCTeAsync(usuario, senha, chaveCTe);
        }
        
        public string RetornaPdfCTesPelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfCTesPelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaPdfCTesPelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfCTesPelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaPdfCTesPelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfCTesPelaEntrada(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaPdfCTesPelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfCTesPelaEntradaAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string DownloadPdfNfse(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento) {
            return base.Channel.DownloadPdfNfse(usuario, senha, NumeroDocumento, DataEmissaoDocumento, CNPJEmissorDocumento);
        }
        
        public System.Threading.Tasks.Task<string> DownloadPdfNfseAsync(string usuario, string senha, string NumeroDocumento, string DataEmissaoDocumento, string CNPJEmissorDocumento) {
            return base.Channel.DownloadPdfNfseAsync(usuario, senha, NumeroDocumento, DataEmissaoDocumento, CNPJEmissorDocumento);
        }
        
        public string RetornaPdfNFSePelaEmissao(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfNFSePelaEmissao(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaPdfNFSePelaEmissaoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfNFSePelaEmissaoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaPdfNFSePelaEntrada(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfNFSePelaEntrada(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public System.Threading.Tasks.Task<string> RetornaPdfNFSePelaEntradaAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte) {
            return base.Channel.RetornaPdfNFSePelaEntradaAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte);
        }
        
        public string RetornaChavesCTePelaEntradaPorTipo(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesCTePelaEntradaPorTipo(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public System.Threading.Tasks.Task<string> RetornaChavesCTePelaEntradaPorTipoAsync(string usuario, string senha, string cnpj, string dataDe, string horaDe, string dataAte, string horaAte, string tipo) {
            return base.Channel.RetornaChavesCTePelaEntradaPorTipoAsync(usuario, senha, cnpj, dataDe, horaDe, dataAte, horaAte, tipo);
        }
        
        public TAMINTEGRA.WS_Avalara_Connect.EventoCTeRespDto RealizarManifestoCTe(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoCTeReqDto evento) {
            return base.Channel.RealizarManifestoCTe(usuario, senha, evento);
        }
        
        public System.Threading.Tasks.Task<TAMINTEGRA.WS_Avalara_Connect.EventoCTeRespDto> RealizarManifestoCTeAsync(string usuario, string senha, TAMINTEGRA.WS_Avalara_Connect.EventoCTeReqDto evento) {
            return base.Channel.RealizarManifestoCTeAsync(usuario, senha, evento);
        }
    }
}
